#!/bin/bash
ZVMRUN="zerovm -QP"
MANIFEST=$(mktemp)
DOUT=$(mktemp -d)
FOUT="$DOUT/out"
mkfifo $FOUT
NVRAM=$(mktemp)
trap "{ rm -rf $MANIFEST $DOUT $NVRAM; exit $?; }" SIGINT SIGTERM EXIT
if [ -z "$1" ]; then
cat << EOF
	Simple "shell like" runner for binaries compiled for zerovm

	Usage: $0 <path to zerovm binary> [arg1] @[file1] [arg2] @[file2]
	
	Examples:
	  run in linux:
	    grep 'word' /tmp/some/file > /tmp/output
	  run in zerovm:
	    zvsh grep 'word' @/tmp/some/file > /tmp/output

	  run in linux:
	    cat test.jpg | composite -compose bumpmap logo.jpeg > out.jpg
	  run in zerovm:
	    cat test.jpg | zvsh composite -compose bumpmap @logo.jpeg > out.jpg
	
	Bottom line: use the same command line you have in Linux, just prepend it with "zvsh" and mark down all files in command line with "@" signs

EOF
	exit 1
fi
EXE="$1"
shift
EXENAME=$(basename "$EXE")
cat > "$MANIFEST" << EOF
Version = 20130611
Memory = 419430400, 0
Node = 1
Timeout = 50
Program = $EXE
EOF
while (( $# )); do
	if [[ "${1:0:1}" == "@" ]]; then
		if [[ $(expr index "$1" "=") != "0" ]]; then
			ENVKEY="${1:1}"
			ENVKV=(${ENVKEY//=/ })
			ENVLIST="${ENVLIST}name=${ENVKV[0]}, value=${ENVKV[1]}\n"
			#ENVLIST="${ENVKV[0]},${ENVKV[1]},${ENVLIST}"
		else
			FPATH="${1:1}"
			FNAME=$(basename "$FPATH")
			if [[ "$FPATH" == "$FNAME" ]] || [[ "$FPATH" == "./${FNAME}" ]]; then
				FPATH="$(pwd)/$FPATH"
			fi
			FNAME=$(mktemp -u XXXXXX."$FNAME")
			echo "Channel = $FPATH, /dev/$FNAME, 3, 0, 419430400, 419430400, 419430400, 419430400" >> "$MANIFEST"
			ZVMARGS="$ZVMARGS /dev/$FNAME"
		fi
	else
		ZVMARGS="$ZVMARGS $1"
	fi
	shift
done
cat >> "$MANIFEST" << EOF
Channel = /dev/stdin, /dev/stdin, 0, 0, 419430400, 419430400, 0, 0
Channel = $FOUT, /dev/stdout, 0, 0, 0, 0, 419430400, 419430400
Channel = /dev/stderr, /dev/stderr, 0, 0, 0, 0, 419430400, 419430400
Channel = $NVRAM, /dev/nvram, 1, 0, 419430400, 419430400, 0, 0
EOF
if [ -n "$ENVLIST" ]; then
	echo "[env]" >> $NVRAM
	echo -e "$ENVLIST" >> $NVRAM
fi
echo "[args]" >> $NVRAM
echo -e "args=${EXENAME}${ZVMARGS}\n" >> $NVRAM
cat "$MANIFEST" 1>&2
cat "$NVRAM" 1>&2
cat - | $ZVMRUN "$MANIFEST" 1>&2 &
cat $FOUT
EXT="$?"
exit $EXT

